services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    container_name: projekti-postgresdb
    labels:
      - "postgresdb=true"
    # env_file:
    #   - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      # POSTGRES_HOST: postgresdb
      # POSTGRES_PORT: 5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - projekti

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: projekti-web
    restart: always
    environment:
      HOSTS: ${HOSTS}
      RECAPTCHA_PUBLIC_KEY: ${RECAPTCHA_PUBLIC_KEY}
      RECAPTCHA_PRIVATE_KEY: ${RECAPTCHA_PRIVATE_KEY}
    depends_on:
      - postgresdb
    expose:
      - "8000"
    # ports:
    #   - "8000:8000"
    networks:
      - projekti
    volumes:
      - static_volume:/static
      - media_volume:/media
      
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: projekti-nginx
    depends_on:
      - web
      - postgresdb
    restart: always
    ports:
      - "82:80"
      - "443:443"
    networks:
      - projekti
    volumes:
      - static_volume:/static:ro
      - media_volume:/media:ro

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: projekti-cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TEST_TUNNEL_TOKEN}
    networks:
      - projekti
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: redis:7-alpine
    container_name: projekti-redis
    restart: always
    # environment:
    #   - REDIS_HOST=redis
    #   - REDIS_PORT=6379
    expose:
      - "6379"
    networks:
      - projekti

  
  db-maintenance:
    image: postgres:14
    container_name: projekti-db_maintenance
    depends_on:
      - postgresdb
    environment:
      - PGPASSWORD=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_NAME=${DB_NAME}
      # - DB_HOST=${DB_HOST}
      - DB_HOST=postgresdb
    entrypoint: |
      /bin/sh -c "
      echo 'Maintenance script started. Target time: 03:00 every day.'
      while true; do
        # Aprēķinām sekundes līdz rītdienas 03:00
        TARGET_HOUR=3
        CURRENT_SECOND_OF_DAY=\$(date +%s)
        # Dabūjam nākamās dienas 03:00 unix timestamp
        NEXT_RUN=\$(date -d 'tomorrow 03:00' +%s)
        SECONDS_TO_SLEEP=\$((NEXT_RUN - CURRENT_SECOND_OF_DAY))
        
        echo \"Sleeping for \$SECONDS_TO_SLEEP seconds until 03:00...\"
        sleep \$SECONDS_TO_SLEEP
        
        echo \"Starting maintenance at \$(date)\"
        psql -h \${DB_HOST} -U \${DB_USER} -d \${DB_NAME} -c 'VACUUM ANALYZE;'
        echo \"Maintenance finished.\"
      done
      "
    restart: always
    networks:
      - projekti

networks:
  projekti:
    driver: bridge
    name: projekti

volumes:
  postgres_data:
  static_volume:
  media_volume: